baseURL = 'kite.github.io'
languageCode = 'en-us'
title = 'Kite - AA'
theme = "archie"
copyright = "© Kite"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
favicon = "https://img.icons8.com/lollipop/48/cyber-security.png" 
og_image = "https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
mode = "toggle"
useCDN = true
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
description = "Archie is a Minimal and Clean theme for Hugo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ka1t3/ka1t3.github.io"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
